config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  resources :posts do
    resources :comments
  end

  get 'posts/:id/upvote' => 'posts#upvote', as: :upvote
  get 'posts/:id/downvote' => 'posts#downvote', as: :downvote

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  #does post need to be plural or singular?



end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    @comment = Comment.find(params[:post_id])
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

    def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    if @comment.destroy
      redirect_to post_path(@post)
    else
      redirect_to root_path
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:post_id, :name, :body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.sort_by{|post| post.vote}.reverse
  end

  def show
    @post = Post.find(params[:id])
    @comments = Comment.where(post_id: params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.vote = 0
    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      redirect_to root_path
    else
      redirect_to post_path(@post)
    end
  end

  def upvote
    @post = Post.find(params[:id])
    @post.vote += 1
    @post.save!
    redirect_to root_path
  end

  def downvote
    @post = Post.find(params[:id])
    @post.vote += -1
    @post.save!
    redirect_to root_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :url, :description, :category, :vote)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_cform.html.erb
<div class='form'>
  <%= form_for [@post, @comment] do |f| %>
    <%= f.hidden_field :post_id %>
    <p><%= f.label :name %></p>
    <p><%= f.text_field :name %></p>
    <p><%= f.label :body %></p>
    <p><%= f.text_area :body %></p>
    <p><%= f.submit %></p>
  <% end %>
</div>

app/views/comments/edit.html.erb
<header>
  <h1>not-Reddit: Edit Comment</h1>
  <p class='options'><%= link_to 'Home', root_path %> | <%= link_to 'New Post', new_post_path %></p>
</header>

<%= render partial: 'comments/cform' %>

app/views/comments/new.html.erb
<header>
  <h1>not-Reddit: New Comment</h1>
  <p class='options'><%= link_to 'Home', root_path %> | <%= link_to 'New Post', new_post_path %></p>
</header>

<%= render partial: 'comments/cform' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MiniHack</title>
  <link href='https://fonts.googleapis.com/css?family=Martel:400,800|Open+Sans:400,300,600' rel='stylesheet' type='text/css'>  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<div class='form'>
  <%= form_for @post do |f| %>
    <p class='form-label'><%= f.label :title %></p>
    <p><%= f.text_field :title %></p>
    <p class='form-label'><%= f.label :url %></p>
    <p><%= f.text_field :url %></p>
    <p class='form-label'><%= f.label :description %></p>
    <p><%= f.text_area :description %></p>
    <p class='form-label'><%= f.label :category %></p>
    <p><%= f.select :category, options_for_select([['General', 'General'], ['Tech', 'Tech'],['Funny', 'Funny'],['Entertainment', 'Entertainment'], ['News', 'News']])%></p>
    <p><%= f.submit %><p>
  <% end %>
</div>

app/views/posts/edit.html.erb
<header>
  <h1>not-Reddit: Edit Post</h1>
  <p class='options'><%= link_to 'Home', root_path %> | <%= link_to 'New Post', new_post_path %></p>
</header>

<%= render partial: 'posts/form' %>

<p><%= link_to 'Back', root_path %></p>

app/views/posts/index.html.erb
<header>
  <h1>not-Reddit</h1>
  <p class='options'><%= link_to 'New Post', new_post_path %></p>
</header>

<% @posts.each do |post| %>
  <div class='link-container'>
    <p class='vote'><%= link_to "^", upvote_path(post) %><br><%= post.vote %><br><%= link_to "v", downvote_path(post) %></p>

    <div class='index-view'>
      <h3><%= link_to "#{post.title}", post.url, :target => "_blank" %></h3>
      <p><%= link_to "View Post", post_path(post) %></p>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<header>
  <h1>not-Reddit: New Post</h1>
  <p class='options'><%= link_to 'Home', root_path %></p>
</header>

<%= render partial: 'posts/form' %>

<p><%= link_to 'Back', root_path %></p>

app/views/posts/show.html.erb
<header>
  <h1>not-Reddit: <%= @post.category %></h1>
  <p class='options'><%= link_to 'Home', root_path %></p>
</header>

<div class='show-body'>
  <p class='vote'><%= link_to "^", upvote_path(@post) %><br><%= @post.vote %><br><%= link_to "v", downvote_path(@post) %></p>

  <div class='show-post'>
    <h2><%= @post.title %></h2>
    <p class='link'><%= link_to "#{@post.url}", @post.url, :target => "_blank" %></p>
    <p><%= @post.description %></p>
    <p class='options'><%= link_to 'Comment', new_post_comment_path(@post) %> | <!--
    --><%= link_to 'Edit Post', edit_post_path(@post) %> | <!--
    --><%= link_to 'Delete Post', @post, method: :delete, data: { confirm: 'Are you sure?' } %></p>
  </div>

</div>

<% @comments.each do |comment|  %>
<div class='comment'>
  <h4><%= comment.name %></h4>
  <p><%= comment.body %></p>
  <p class='options'><%= link_to 'Edit Comment', edit_post_comment_path(comment, @post) %> |
  <%= link_to 'Delete Comment', [@post, comment], method: :delete, data: { confirm: 'Are you sure?' } %></p>
</div>  
<% end %>